"""
Game Constants
Defines all magic numbers and constant values used throughout the game
"""

# === PLAYER CONSTANTS ===

# Hitbox sizes (width, height)
PLAYER_HITBOX_NORMAL = (40, 45)
PLAYER_HITBOX_CROUCH = (55, 25)
PLAYER_HITBOX_ROLL = (35, 35)

# Hitbox offsets (how far up the hitbox is from rect bottom)
PLAYER_HITBOX_OFFSET_NORMAL = 90
PLAYER_HITBOX_OFFSET_CROUCH = 70
PLAYER_HITBOX_OFFSET_ROLL = 72

# Movement
PLAYER_SPEED = 4
PLAYER_GRAVITY = 0.6
PLAYER_JUMP_STRENGTH = -13
PLAYER_DOUBLE_JUMP_MULTIPLIER = 0.9
PLAYER_VARIABLE_JUMP_DAMPENING = 0.4

# Roll mechanics
PLAYER_ROLL_SPEED_INITIAL = 7
PLAYER_ROLL_SPEED_MAX = 12
PLAYER_ROLL_SPEED_ACCELERATION = 0.15
PLAYER_ROLL_STAMINA_MAX = 120
PLAYER_ROLL_STAMINA_RECHARGE_RATE = 0.4
PLAYER_ROLL_STAMINA_RECHARGE_DELAY = 30  # frames
PLAYER_ROLL_COOLDOWN = 0  # frames

# Spin attack
PLAYER_SPIN_CHARGES_MAX = 3
PLAYER_SPIN_CHARGE_COOLDOWN = 180  # frames (3 seconds at 60 FPS)
PLAYER_SPIN_SPEED = 10
PLAYER_SPIN_DURATION_FRAMES = 7  # Number of animation frames
PLAYER_SPIN_ANIMATION_FPS = 20

# Health and damage
PLAYER_MAX_HEALTH = 6  # 3 hearts
PLAYER_INVINCIBLE_DURATION = 35  # frames
PLAYER_HURT_DURATION = 30  # frames
PLAYER_KNOCKBACK_STRENGTH = 20
PLAYER_KNOCKBACK_Y_BOOST = -5

# Animation
PLAYER_ANIMATION_SPEED_WALK = 0.15
PLAYER_ANIMATION_SPEED_IDLE = 0.1
PLAYER_ANIMATION_SPEED_ROLL = 0.25
PLAYER_ANIMATION_SPEED_SPIN = 0.3
PLAYER_ANIMATION_SPEED_FLAP = 0.3
PLAYER_ANIMATION_SPEED_HURT = 0.2

# Sprite heights
PLAYER_SPRITE_HEIGHT_NORMAL = 180
PLAYER_SPRITE_HEIGHT_CROUCH = 145
PLAYER_SPRITE_HEIGHT_ROLL = 145


# === ENEMY CONSTANTS ===

# Snowy (Snowman) enemy
SNOWY_HEALTH = 2
SNOWY_SPEED = 0.6
SNOWY_CHASE_SPEED = 1.0
SNOWY_TRACKING_RANGE = 500
SNOWY_ATTACK_RANGE = 90
SNOWY_LOSE_INTEREST_RANGE = 800
SNOWY_PUNCH_DAMAGE = 2
SNOWY_ATTACK_COOLDOWN_MIN = 80
SNOWY_ATTACK_COOLDOWN_MAX = 140
SNOWY_ATTACK_PAUSE_DURATION = 35

# Generic enemy defaults
ENEMY_GRAVITY = 0.6
ENEMY_INVINCIBLE_DURATION = 60  # frames
ENEMY_HURT_FLASH_DURATION = 20  # frames


# === COLLISION CONSTANTS ===

# Collision tolerances
PLATFORM_COLLISION_TOLERANCE = 5  # pixels
STOMP_DETECTION_TOLERANCE = 15  # pixels above enemy head

# Bounce
STOMP_BOUNCE_VELOCITY = -10


# === GAME MECHANICS ===

# Camera
CAMERA_OFFSET_X = 300  # Player offset from left edge

# Death and respawn
DEATH_ANIMATION_DELAY = 90  # frames (1.5 seconds at 60 FPS)
DEATH_FADE_SPEED = 5
PIT_DEATH_Y_THRESHOLD = 550  # Y position below which is pit death

# Projectile sounds
PROJECTILE_SOUND_RANGE = 400  # Distance within which projectile sounds are heard


# === LEVEL CONSTANTS ===

# Level dimensions (these vary by level, but common defaults)
DEFAULT_LEVEL_HEIGHT = 600
DEFAULT_GROUND_Y = 570
DEFAULT_GROUND_HEIGHT = 30


# === AUDIO CONSTANTS ===

# Volume levels (0.0 to 1.0)
VOLUME_MUSIC_DEFAULT = 0.6
VOLUME_DEATH = 0.6
VOLUME_STAGE_CLEAR = 0.7
VOLUME_JUMP = 0.4
VOLUME_DOUBLE_JUMP = 0.4
VOLUME_COIN = 0.2
VOLUME_BUMP = 0.2
VOLUME_LAND_ENEMY = 0.3
VOLUME_LAND_SLIME = 0.3
VOLUME_ENEMY_PROJECTILE = 0.2
VOLUME_SPIN_ATTACK = 0.3


# === UI CONSTANTS ===

# Font sizes
FONT_SIZE_TITLE = 48
FONT_SIZE_LARGE = 32
FONT_SIZE_MEDIUM = 24
FONT_SIZE_SMALL = 16
FONT_SIZE_TINY = 12

# HUD positioning
HUD_MARGIN_TOP = 10
HUD_MARGIN_LEFT = 10
HUD_SPACING = 35


# === RENDERING CONSTANTS ===

# Platform brick dimensions
BRICK_WIDTH = 32
BRICK_HEIGHT = 16

# Colors (R, G, B)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GOLD = (255, 215, 0)
COLOR_RED = (255, 50, 50)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 100, 255)

# Snowy/icy brick colors
COLOR_BRICK_ICY = (200, 220, 240)
COLOR_BRICK_HIGHLIGHT = (240, 250, 255)
COLOR_BRICK_SHADOW = (120, 140, 170)
COLOR_BRICK_OUTLINE = (100, 120, 150)

# Dark icy brick colors
COLOR_DARK_ICY_BRICK = (50, 100, 150)
COLOR_DARK_ICY_HIGHLIGHT = (70, 120, 180)
COLOR_DARK_ICY_SHADOW = (30, 70, 110)
COLOR_DARK_ICY_OUTLINE = (20, 50, 90)

# Snowy ground colors
COLOR_SNOWY_BRICK = (255, 255, 255)
COLOR_SNOWY_HIGHLIGHT = (245, 250, 255)
COLOR_SNOWY_SHADOW = (220, 230, 240)
COLOR_SNOWY_OUTLINE = (200, 210, 220)
